### ISSUE TITLE
#Waow

### ISSUE THREAD

**Issue by P1erreGaultier** [orichalque/TestImpact#1]
Its such a great work!
How can you be so good?
#JeanMichelLeCanard

Cheers <3

**Comment by orichalque** [comment]
Well... It's just a demo of the usage of an impact model introduced in my paper, the camera ready version isn't available yet, I'll notify you if you want to have a look ;) 

#JeanMichelIsStillAliveAndWaitsForYou

**Comment by P1erreGaultier** [comment]
Much love and have fun ! <3
Snoopy Doggy forever in our hearts <3

Kisses

#JuanMiguelElCanardoWillBeback
